config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :items
  resources :clubs
  resources :positions
  devise_for :members, :controllers => { :registrations => "registrations" }
  get '/members/my_dashboard', to: 'members#my_dashboard'
  get '/members/new_member', to: 'members#new_member'
  delete '/members/:id', to: 'members#destroy_member'
  match '/orders/:id/edit_status', via: %w[get post patch], to: "orders#edit_status"
  get '/about', to: 'pages#about'
  get '/items/:id/orders', to: 'items#item_history'
  root to: 'members#my_dashboard'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/club.rb
class Club < ApplicationRecord
    has_many :items
    has_many :members
    has_many :orders
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_action :check_login
  before_action :check_admin, only: %i[ show edit update destroy ] 
  def check_login
    redirect_to member_session_path and return unless current_member
  end
  before_action :set_club, only: %i[ show edit update destroy ]

  # GET /clubs/1 or /clubs/1.json
  def show
    @all_orders = Order.where(item_id: @club.items.pluck(:id))
    @all_items = @club.items
    @all_members = @club.members
  end

  # GET /clubs/new
  def new
    @club = Club.new
  end

  # GET /clubs/1/edit
  def edit
  end

  # POST /clubs or /clubs.json
  def create
    @club = Club.new(club_params)

    respond_to do |format|
      if @club.save
        format.html { redirect_to @club, notice: "Club was successfully created." }
        format.json { render :show, status: :created, location: @club }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clubs/1 or /clubs/1.json
  def update
    respond_to do |format|
      if @club.update(club_params)
        format.html { redirect_to @club, notice: "Club was successfully updated." }
        format.json { render :show, status: :ok, location: @club }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clubs/1 or /clubs/1.json
  def destroy
    @club.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: "Club was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_club
      @club = Club.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def club_params
      params.require(:club).permit(:name, :room_name)
    end

    # params : {
    #   club : {
    #     name, room_name,....
    #   }, commit: "sdsdsd"
    # }

    # request: {
    #   metadata: {},
    #   ....
    #   params: {id, name, room_name},
    #   format:
    #   method:
    # }

    def check_admin
      if current_member.is_admin? 
        redirect_to root_path,alert:"You are not authorized to view this page."
        return
      end  
    end
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/views/clubs/_form.html.erb
<%= form_with(model: club) do |form| %>
  <% if club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(club.errors.count, "error") %> prohibited this club from being saved:</h2>

      <ul>
        <% club.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :room_name %>
    <%= form.text_field :room_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clubs/edit.html.erb
<h1>Editing Club</h1>

<%= render 'form', club: @club %>

<%= link_to 'Show', @club %> |
<%= link_to 'Back', clubs_path %>

app/views/clubs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clubs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Room name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clubs.each do |club| %>
      <tr>
        <td><%= club.name %></td>
        <td><%= club.room_name %></td>
        <td><%= link_to 'Show', club %></td>
        <td><%= link_to 'Edit', edit_club_path(club) %></td>
        <td><%= link_to 'Destroy', club, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Club', new_club_path %>

app/views/clubs/new.html.erb
<h1>New Club</h1>

<%= render 'form', club: @club %>

<%= link_to 'Back', clubs_path %>

app/views/clubs/show.html.erb
<p id="notice"><%= notice %></p>

<div class="main-card mb-3 card mt-4 card-hover-shadow">
  <div class="card-header">
    <div class="card-header-title">
      <i class="fa fa-list mr-2"></i>
      Club Members
    </div>
  </div>

  <div class="card-body overflow-auto">
    <div id="table_content">
      <table id="members" class="table text-center table-striped table-bordered">
        <thead>
        <tr>
          <th> No. </th>
          <th> Name </th>
          <th> Position </th>
          <th> Action </th>
        </tr>
        </thead>

        <tbody>
        <% @all_members.select {|m| m.active }.select { |m| m.active }.each_with_index do |member, index| %>
          <tr>
            <td><%= index+1 %></td>
            <td><%= member.name %></td>
            <td><%= member.position.name %></td>
            <td>
              <% if member.id != current_member.id %>
                <%= link_to '<i class="fa fa-trash m-1" aria-hidden="true"></i> Remove'.html_safe, url_for(controller: "members", action: "destroy_member", id: member.id), data: {confirm: "Are you sure?"}, method: :delete, class: "btn m-1 btn-danger btn-shadow btn-wide" %>
              <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>

    </div>
  </div>
</div>

<div class="main-card mb-3 card mt-4 card-hover-shadow">
  <div class="card-header">
    <div class="card-header-title">
      <i class="fa fa-list mr-2"></i>
      Club Items
    </div>
  </div>

  <div class="card-body overflow-auto">
    <div id="table_content">
      <table id="items" class="table text-center table-striped table-bordered">
        <thead>
        <tr>
          <th> No. </th>
          <th> Item </th>
          <th> Quantity </th>
          <th> Number of Orders </th>
          <th> Action </th>
        </tr>
        </thead>

        <tbody>
        <% @all_items.each_with_index do |item, index| %>
          <tr>
            <td><%= index+1 %></td>
            <td><%= item.name %></td>
            <td><%= item.units %></td>
            <td><%= item.orders.count %></td>
            <td>
              <% if current_member.is_admin? %>
                <%= link_to '<i class="fa fa-trash m-1" aria-hidden="true"></i> Remove'.html_safe, url_for(controller: "items", action: "destroy", id: item.id), data: {confirm: "Are you sure?"}, method: :delete, class: "btn m-1 btn-danger btn-shadow btn-wide" %>
                <%= link_to '<i class="fa fa-edit m-1" aria-hidden="true"></i> Edit'.html_safe, url_for(controller: "items", action: "edit", id: item.id), class: "btn m-1 btn-primary btn-shadow btn-wide" %>
              <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<div class="main-card mb-3 card mt-4 card-hover-shadow">
  <div class="card-header">
    <div class="card-header-title">
      <i class="fa fa-list mr-2"></i>
      Club Orders
    </div>
  </div>

  <div class="card-body overflow-auto">
    <div id="table_content">
      <table id="orders" class="table text-center table-striped table-bordered">
        <thead>
        <tr>
          <th> No. </th>
          <th> Item </th>
          <th> Quantity </th>
          <th> Requested At </th>
          <th> Requested By </th>
          <th> Approved At </th>
          <th> Approved By </th>
          <th> Returned </th>
          <th> Action </th>
        </tr>
        </thead>

        <tbody>
        <% @all_orders.each_with_index do |order, index| %>
          <tr>
            <td><%= index+1 %></td>
            <td><%= order.item.name %></td>
            <td><%= order.quantity %></td>
            <td><%= order.requested_at %></td>
            <td><%= order.requester.name %></td>
            <td><%= order.approved_at %></td>
            <td><%= order.approver.name %></td>
            <td><%= order.returned ? "Yes" : "No" %></td>
            <td>
                <% if order.approver.id == 1 && order.requester == current_member %>
                  <%= link_to '<i class="fa fa-trash m-1" aria-hidden="true"></i> Delete'.html_safe, url_for(controller: "orders", action: "destroy", id: order.id), data: {confirm: "Are you sure?"}, method: :delete, class: "btn m-1 btn-danger btn-shadow btn-wide" %>
                <% elsif current_member.is_admin? %>
                  <%= link_to '<i class="fa fa-edit m-1" aria-hidden="true"></i> Approve / Delete'.html_safe, url_for(controller: "orders", action: "status", id: order.id), class: "btn m-1 btn-danger btn-shadow btn-wide" %>
                <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>

    </div>
  </div>
</div>

<script>
    $(document).ready(function () {
        $("#members, #orders, #items").DataTable({
            autoWidth: true,
            dom: "ftp",
            "oLanguage": {
                "sSearch": "<b> Search : </b>",
                "sEmptyTable": "There is nothing to show here.",
                pageLength: 5
            }
        });
    });
</script>