config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :items
  resources :clubs
  resources :positions
  devise_for :members, :controllers => { :registrations => "registrations" }
  get '/members/my_dashboard', to: 'members#my_dashboard'
  get '/members/new_member', to: 'members#new_member'
  delete '/members/:id', to: 'members#destroy_member'
  match '/orders/:id/edit_status', via: %w[get post patch], to: "orders#edit_status"
  get '/about', to: 'pages#about'
  get '/items/:id/orders', to: 'items#item_history'
  root to: 'members#my_dashboard'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/position.rb
class Position < ApplicationRecord
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :check_login
  def check_login
    redirect_to member_session_path and return unless current_member&.position&.name == "DB Manager"
  end
  before_action :set_position, only: %i[ show edit update destroy ]

  # GET /positions or /positions.json
  def index
    @positions = Position.all
  end

  # GET /positions/1 or /positions/1.json
  def show
  end

  # GET /positions/new
  def new
    @position = Position.new
  end

  # GET /positions/1/edit
  def edit
  end

  # POST /positions or /positions.json
  def create
    @position = Position.new(position_params)

    respond_to do |format|
      if @position.save
        format.html { redirect_to @position, notice: "Position was successfully created." }
        format.json { render :show, status: :created, location: @position }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /positions/1 or /positions/1.json
  def update
    respond_to do |format|
      if @position.update(position_params)
        format.html { redirect_to @position, notice: "Position was successfully updated." }
        format.json { render :show, status: :ok, location: @position }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /positions/1 or /positions/1.json
  def destroy
    @position.destroy
    respond_to do |format|
      format.html { redirect_to positions_url, notice: "Position was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_position
      @position = Position.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def position_params
      params.require(:position).permit(:name)
    end
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/views/positions/_form.html.erb
<div class="main-card mb-3 card mt-4 card-hover-shadow">
  <div class="card-header">
    <div class="card-header-title">
      <i class="fa fa-edit mr-2"></i>
      Position Form
    </div>
  </div>

  <div class="card-body overflow-auto">
    <%= form_with(model: position) do |f| %>

      <div class="mb-3">
        <div><%= f.label :name, class: "col-form-label" %></div>
        <div><%= f.text_field :name, autofocus: true, class: "form-control" %></div>
      </div>

      <%= f.submit "Submit", class: "mt-3 col-lg-12 btn btn-success p-2" %>
    <% end %>
  </div>
</div>

app/views/positions/edit.html.erb
<h1>Editing Position</h1>
<%= render 'form', position: @position %>

app/views/positions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Positions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @positions.each do |position| %>
      <tr>
        <td><%= position.name %></td>
        <td><%= link_to 'Show', position %></td>
        <td><%= link_to 'Edit', edit_position_path(position) %></td>
        <td><%= link_to 'Destroy', position, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Position', new_position_path %>

app/views/positions/new.html.erb
<h1>New Position</h1>
<%= render 'form', position: @position %>

app/views/positions/show.html.erb
<div class="main-card mb-3 card mt-4 card-hover-shadow">
  <div class="card-header">
    <div class="card-header-title">
      <i class="fa fa-list mr-2"></i>
      Position Information
    </div>
  </div>

  <div class="card-body overflow-auto">
    <div class="row">
      <div class="col-lg-4"><strong>Position Name</strong></div>
      <div class="col-lg-8"><%= @position.name %></div>
    </div>
    <div class="row col-lg-12 mt-2 align-content-center">
      <div class="btn-group" role="group">
        <%= link_to '<i class="fa fa-edit m-1" aria-hidden="true"></i> Edit Position'.html_safe, edit_position_path(@position), class: "btn m-1 btn-outline-primary btn-shadow btn-wide" %>
        <%= link_to '<i class="fa fa-trash m-1" aria-hidden="true"></i> Destroy Position'.html_safe, positions_path(id: @position.id, method: :delete), data: {confirm: "Are you sure? This will destroy all associated members and their information as well."}, class: "btn m-1 btn-outline-danger btn-shadow btn-wide" %>
      </div>
    </div>
  </div>
</div>