config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :items
  resources :clubs
  resources :positions
  devise_for :members, :controllers => { :registrations => "registrations" }
  get '/members/my_dashboard', to: 'members#my_dashboard'
  get '/members/new_member', to: 'members#new_member'
  delete '/members/:id', to: 'members#destroy_member'
  match '/orders/:id/edit_status', via: %w[get post patch], to: "orders#edit_status"
  get '/about', to: 'pages#about'
  get '/items/:id/orders', to: 'items#item_history'
  root to: 'members#my_dashboard'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :club
  has_many :orders
  default_scope -> { where(archived: [false, nil]) }
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :check_login
  def check_login
    redirect_to member_session_path and return unless current_member
  end
  before_action :set_item, only: %i[ show edit update destroy ]

  # GET /items or /items.json
  def index
    @items = current_member.club.items.where.not(units:0)
  end

  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end
  def item_history
    @current_item = Item.unscoped.find(params[:id])
    @item_history = @current_item.orders
  end  
  # POST /items or /items.json
  def create
    params[:item][:club_id] = current_member.club.id
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to items_path, notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    params[:item][:club_id] = current_member.club.id
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to items_path, notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.update(archived: true)
    respond_to do |format|
      format.html { redirect_to items_path, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.unscoped.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:name, :units, :club_id)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<div class="card-body overflow-auto">
  <%= form_with(model: item) do |f| %>

    <div class="mb-3">
      <div><%= f.label :name, class: "col-form-label" %></div>
      <div><%= f.text_field :name, class: "form-control" %></div>
    </div>

    <div class="mb-3">
      <div><%= f.label :units, class: "col-form-label" %></div>
      <div><%= f.number_field :units, class: "form-control" %></div>
    </div>

    <%= f.submit "Submit", class: "mt-3 col-lg-12 btn btn-success p-2" %>
  <% end %>
</div>

app/views/items/edit.html.erb
<% if @item.errors.any? %>
  <div class="alert alert-danger pt-3 pb-3 mb-0">
    <strong>The following errors prevented the action</strong>
    <ul class="mb-0">
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="main-card mb-3 card mt-4 card-hover-shadow">
  <div class="card-header">
    <div class="card-header-title">
      <i class="fa fa-edit mr-2"></i>
      Edit Item Form
    </div>
  </div>
  <%= render 'form', item: @item %>
</div>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<div class="main-card mb-3 card mt-4 card-hover-shadow">
  <div class="card-header">
    <div class="card-header-title">
      <i class="fa fa-list mr-2"></i>
      Add a New Item
    </div>
  </div>

  <div class="card-body overflow-auto">
    <div class="row">
      <div class="col-lg-4"><strong>Club Name</strong></div>
      <div class="col-lg-8"><%= current_member.club.name %></div>
    </div>
    <div class="row col-lg-12 mt-2 align-content-center">
      <div class="btn-group" role="group">
        <%= link_to '<i class="fa fa-plus m-1" aria-hidden="true"></i> New Item Addition'.html_safe, new_item_path, class: "btn m-1 btn-outline-success btn-shadow btn-wide" %>
      </div>
    </div>
  </div>
</div>

<div class="main-card mb-3 card mt-4 card-hover-shadow">
  <div class="card-header">
    <div class="card-header-title">
      <i class="fa fa-list mr-2"></i>
      Club Inventory Items
    </div>
  </div>

  <div class="card-body overflow-auto">
    <div id="table_content">
      <table id="items" class="table text-center table-striped table-bordered">
        <thead>
        <tr>
          <th> No. </th>
          <th> Item Name </th>
          <th> Quantity </th>
          <th> Club </th>
          <th> Action </th>
        </tr>
        </thead>

        <tbody>
        <% @items.each_with_index do |item, index| %>
          <tr>
            <td><%= index+1 %></td>
            <td><%= item.name %></td>
            <td><%= item.units %></td>
            <td><%= item.club.name %></td>
            <td>
              <%= link_to 'Order History'.html_safe, '/items/'+item.id.to_s+'/orders', class: "btn btn-primary" %>
              <% if current_member.is_admin? %>
                <%= link_to 'Delete Item'.html_safe, url_for(controller: "items", action: "destroy", id: item.id), data: {confirm: "Are you sure?"}, method: :delete, class: "btn btn-danger" %>
                <%= link_to 'Edit Item'.html_safe, edit_item_path(item), class: "btn btn-secondary" %>
              <%end%>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<script>
    $(document).ready(function () {
        $("#items").DataTable({
            autoWidth: true,
            dom: "ftp",
            "oLanguage": {
                "sSearch": "<b> Search by Item Name : </b>",
                "sEmptyTable": "There is nothing to show here.",
                pageLength: 10
            }
        });
    });
</script>

app/views/items/item_history.html.erb
<div class="main-card mb-3 card mt-4 card-hover-shadow">
  <div class="card-header">
    <div class="card-header-title">
      <i class="fa fa-list mr-2"></i>
      Item Information
    </div>
  </div>

  <div class="card-body overflow-auto">
    <div class="row">
      <div class="col-lg-4"><strong>Item Name</strong></div>
      <div class="col-lg-8"><%= @current_item.name %></div>
    </div>
    <div class="row">
      <div class="col-lg-4"><strong>Quantity</strong></div>
      <div class="col-lg-8"><%= @current_item.units %></div>
    </div>
  </div>
</div>

<div class="main-card mb-3 card mt-4 card-hover-shadow">
  <div class="card-header">
    <div class="card-header-title">
      <i class="fa fa-list mr-2"></i>
      Item History
    </div>
  </div>

  <div class="card-body overflow-auto">
    <div id="table_content">
      <table id="item_history_table" class="table text-center table-striped table-bordered">
        <thead>
          <tr>
            <th> No. </th>
            <th> Item </th>
            <th> Quantity </th>
            <th> Requested At </th>
            <th> Approved At </th>
            <th> Deadline </th>
            <th> Returned </th>
          </tr>
        </thead>

        <tbody>
          <% @item_history.each_with_index do |order, index| %>
            <tr>
              <td><%= index+1 %></td>
              <td><%= order.item.name %></td>
              <td><%= order.quantity %></td>
              <td><%= order.requested_at %></td>
              <td><%= order.approved_at %></td>
              <td><%= order.deadline %></td>
              <td><%= order.returned ? "Yes" : "No" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<script>
    $(document).ready(function () {
        $("#item_history_table").DataTable({
            autoWidth: true,
            dom: "ftp",
            "oLanguage": {
                "sSearch": "<b> Search : </b>",
                "sEmptyTable": "There is nothing to show here.",
                pageLength: 5
            }
        });
    });
</script>

app/views/items/new.html.erb
<% if @item.errors.any? %>
  <div class="alert alert-danger pt-3 pb-3 mb-0">
    <strong>The following errors prevented the action</strong>
    <ul class="mb-0">
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="main-card mb-3 card mt-4 card-hover-shadow">
  <div class="card-header">
    <div class="card-header-title">
      <i class="fa fa-edit mr-2"></i>
      New Item Form
    </div>
  </div>
  <%= render 'form', item: @item %>
</div>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Units:</strong>
  <%= @item.units %>
</p>

<p>
  <strong>Club:</strong>
  <%= @item.club_id %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>